require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "This is an example"
task :example do
  puts "Hi y'all! We just wrote a rake task! :D"
end
